---
- name: Creating users & files and dirctory  in users home directory
  hosts: all
  tasks:
   - name: create users
     user: 
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: Creating files and directory 
     file:
      name: "{{d}}"           
      state: "{{e}}"

     
