---
- name: Working on tomcat
  hosts: all
  tasks:
   - name: Start tomcat as a container
     docker_container:
      image: tomcat
      name: mytomcat
   - name: Wait for 2sec
     pause:
      seconds: 2
   - name: Stop tomcat container
     docker_container: 
      name: mytomcat
      state: stopped
   - name: Remove the tomcat container
     docker_container:
      name: mytomcat
      state: absent
